
spring:
  datasource:
    #基本属性
    url: jdbc:mysql://localhost:3306/flowable-db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

# mybatis-plus相关配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
