server:
  port: 8001
  servlet:
    context-path: /flowable-design

flowable:
  # flowable 取消spring boot时自动部署resource/processes中的流程文件
  check-process-definitions: false
  # 自动生成flowable相关表 第一次生成后建议关闭提高运行速度
  database-schema-update: false
  # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
  history-level: full
  # 设置成宋体
  activity-font-name: \u5B8B\u4F53
  label-font-name: \u5B8B\u4F53
  annotation-font-name: \u5B8B\u4F53
  common:
    app:
      idm-url: http://localhost:8080/flowable-idm
      idm-admin:
        user: admin
        password: test